from __future__ import annotations

# Centralized deck data so the UI logic stays focused on rendering and interactions.
MEDICAL_DECKS: dict[str, list[dict[str, str]]] = {
    "Abdomen and GI": [
        {"front": "Hematemesis", "back": "Vomiting blood; if exposed to gastric acid it may look like coffee grounds."},
        {"front": "Dysphagia", "back": "Difficulty swallowing."},
        {"front": "Odynophagia", "back": "Painful swallowing."},
        {"front": "Aerophagia", "back": "Excessive flatus from swallowed air."},
        {"front": "Icterus (jaundice)", "back": "Associated with hepatitis, biliary cirrhosis, or gallstones."},
        {"front": "Anorexia", "back": "Loss of appetite."},
        {"front": "Expected skin finding (abdomen)", "back": "Skin should be smooth, dry, and even in tone (or lighter from less sun)."},
        {"front": "Unexpected skin findings", "back": "Bruising, dilated veins, rashes, or yellowing are concerning."},
        {"front": "Symmetry and masses expected", "back": "Abdominal movement should be symmetric with no masses."},
        {"front": "Symmetry unexpected", "back": "Localized bulging, mass, or asymmetric movement is abnormal."},
        {"front": "Shape and contour expected", "back": "Flat, even, slightly convex, or rounded can be normal."},
        {"front": "Shape variation in thin body frame", "back": "Scaphoid contour can be a normal variation."},
        {"front": "Shape variation in obese patients", "back": "Increased subcutaneous fat changes contour."},
        {"front": "Shape variation in older adults", "back": "Decreased muscle tone can change contour."},
        {"front": "Shape unexpected", "back": "Marked distention or severe concavity is abnormal."},
        {"front": "Umbilicus expected", "back": "Midline and usually inverted."},
        {"front": "Umbilicus variation", "back": "Piercing or mild extraversion may be a variation."},
        {"front": "Umbilicus unexpected", "back": "Redness, swelling, discoloration, or lesions are abnormal."},
        {"front": "Exercise and constipation", "back": "Sedentary lifestyle increases constipation risk; walking 30 minutes daily helps."},
        {"front": "Diet advice for bowel health", "back": "Balanced high-fiber diet and about 8 to 10 glasses of water per day."},
        {"front": "Colorectal screening age", "back": "Routine screening is recommended around age 50, earlier if high risk."},
        {"front": "Stool and scope testing", "back": "Check stool for blood; use sigmoidoscopy, colonoscopy, or barium enema."},
        {"front": "Probiotics", "back": "Promote beneficial microorganisms in the GI tract."},
        {"front": "Pediatric GI history: stool questions", "back": "Ask stool frequency, constipation, pain, and tolerance of new foods."},
        {"front": "Pediatric GI history: nutrition questions", "back": "Ask current diet, water intake, and infant feeding tolerance."},
        {"front": "Melena", "back": "Dark, tarry stool from upper GI bleeding."},
        {"front": "Tarry stool without melena", "back": "Iron can cause dark/tarry stool appearance."},
        {"front": "Black non-tarry stool causes", "back": "Pepto-Bismol, black licorice, or blueberries can darken stool."},
        {"front": "Hematochezia", "back": "Bright red blood, often from rectum, anus, or sigmoid."},
        {"front": "Red hematemesis", "back": "Vomiting fresh blood."},
        {"front": "Steatorrhea", "back": "Fatty diarrheal stool."},
        {"front": "Pale or clay stool", "back": "May indicate impaired biliary production/flow."},
        {"front": "Meconium", "back": "First stool, usually passed in the first 24 to 48 hours."},
        {"front": "Gastrocolic reflex", "back": "Peristalsis is stimulated after eating."},
        {"front": "Fecal occult blood testing", "back": "Common recommendation is yearly screening."},
        {"front": "Flexible sigmoidoscopy schedule", "back": "Often every 5 years with rectal exam."},
        {"front": "Double contrast barium enema schedule", "back": "Often every 5 years."},
        {"front": "Colonoscopy schedule", "back": "Often every 10 years for average risk screening."},
        {"front": "Abdominal percussion expected", "back": "Tympany predominates; dullness is expected over organs or stool."},
        {"front": "Abdominal pain triage question", "back": "Assess onset, location, radiation, timing, severity, and aggravating factors."},
    ],
    "Rectum and Genitourinary": [
        {"front": "Kidney functions", "back": "Maintain fluid and electrolyte balance, support red blood cell production, and filter waste."},
        {"front": "Ureters", "back": "Transport urine from kidneys to bladder."},
        {"front": "Bladder role", "back": "Stores urine; urge to void commonly appears near 300 mL."},
        {"front": "Urethra role", "back": "Passageway for urine; in males it also carries semen."},
        {"front": "Urinary retention", "back": "Inability to empty the bladder."},
        {"front": "Urinary hesitancy", "back": "Trouble starting urination."},
        {"front": "Urinary urgency", "back": "Inability to wait to urinate."},
        {"front": "Dribbling", "back": "Leakage before or after full urinary stream."},
        {"front": "Urinary frequency", "back": "Voiding more often than normal."},
        {"front": "Nocturia", "back": "Urinating repeatedly during the night."},
        {"front": "Incontinence", "back": "Loss of bladder control."},
        {"front": "Urge incontinence", "back": "Leakage related to sudden urge and poor control."},
        {"front": "Stress incontinence", "back": "Leakage with coughing, sneezing, or exertion."},
        {"front": "Nulliparous cervix", "back": "Usually smooth with a small circular os."},
        {"front": "Parous cervix", "back": "Os may be larger and more irregular after childbirth."},
        {"front": "Urinary interview basics", "back": "Ask about stream, urgency, frequency, pain, and foul odor."},
        {"front": "Anorectal interview basics", "back": "Ask about hemorrhoids, stool changes, blood/pus/mucus, and bowel routine."},
        {"front": "Reproductive interview basics", "back": "Ask nonjudgmentally about identity/practices, menstrual history, and exam frequency."},
        {"front": "Pelvic exam position", "back": "Supine, knees bent, feet supported; ensure privacy and comfort."},
        {"front": "Pelvic exam preparation", "back": "Client should void before exam; explain each step with gentle but firm technique."},
        {"front": "Mons pubis unexpected", "back": "Swelling, redness, lesions, ulcerations, patchy hair loss, or pubic lice."},
        {"front": "Labia and vestibule unexpected", "back": "Inflammation, ulceration, malodorous discharge, tenderness, white patches, or lumps."},
        {"front": "Cystocele", "back": "Bladder prolapse into vagina with pressure or stress incontinence."},
        {"front": "Rectocele", "back": "Rectal prolapse into vagina with pressure and possible constipation."},
        {"front": "Goodell sign", "back": "Softening of the cervix around 4 to 6 weeks gestation."},
        {"front": "Chadwick sign", "back": "Cyanotic vaginal mucosa and cervix around 6 to 8 weeks gestation."},
        {"front": "Hegar sign", "back": "Softening of uterine isthmus around 4 to 6 weeks and into first trimester."},
        {"front": "Mucus plug", "back": "Thick cervical mucus that protects fetus from infection and may pass as bloody show."},
        {"front": "Female puberty onset", "back": "Usually begins around ages 8 to 12, often with thelarche (breast budding)."},
        {"front": "Menopause", "back": "Permanent cessation of menses, often around ages 48 to 51."},
        {"front": "Hypospadias", "back": "Urethral meatus located on ventral side of penis."},
        {"front": "Epispadias", "back": "Urethral meatus located on dorsal side of penis."},
        {"front": "External hemorrhoids", "back": "Dilated veins at anal opening, often from straining."},
        {"front": "Thrombosed hemorrhoid", "back": "Bluish-purple painful swelling from a blood clot."},
        {"front": "Rectal prolapse", "back": "Partial or complete protrusion of rectal wall through anal opening."},
        {"front": "Hydrocele", "back": "Fluid collection around testicle causing usually painless swelling."},
        {"front": "Peyronie disease", "back": "Fibrous plaque in penile tissue causing curvature, often after repeated injury."},
        {"front": "Cryptorchidism", "back": "Undescended testes."},
        {"front": "Phimosis", "back": "Foreskin cannot retract over the glans."},
        {"front": "Paraphimosis", "back": "Retracted foreskin trapped behind glans; this is a medical emergency."},
        {"front": "Priapism", "back": "Painful prolonged erection unrelated to sexual arousal."},
        {"front": "Acute urinary retention", "back": "Emergency with painful urge, abdominal swelling, and inability to void."},
        {"front": "Chronic urinary retention", "back": "Frequency, hesitancy, intermittent stream, and post-void urgency."},
        {"front": "Pilonidal cyst", "back": "Hair-containing cyst over coccyx; may open as a dimple."},
        {"front": "HPV vaccine", "back": "Gardasil helps prevent HPV-related cancers and is recommended before sexual activity."},
        {"front": "Hepatitis B vaccine", "back": "Recommended for exposure risk because Hep B spreads by bodily fluids."},
        {"front": "Contraception categories", "back": "Natural, barrier, pharmacologic, and surgical methods."},
        {"front": "HIV screening guidance", "back": "Screen ages 15 to 75 and during pregnancy; high-risk clients should test annually."},
    ],
}

